# Generated by Django 3.0.5 on 2024-01-30 11:56

from django.db import migrations, models
import simple_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_api', '0002_auto_20240130_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=simple_api.models.generate_sequential_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
